name: Go-SVM's CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          stable: true
          go-version: "1.15"
      - name: Checkout sources
        uses: actions/checkout@v2
      - run: |
          set -e
          make download
          make test
