name: Go-SVM's CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Download SVM artifacts
        run: |
          set -e
          echo '${{ secrets.GITHUB_TOKEN }}' | gh auth login --with-token
          ./download_artifacts.sh
      - working-directory: svm
        run: go test .
