name: Go-SVM's CI

on: [push, pull_request]

jobs:
  test:
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Test
        working-directory: svm
        run: go test .
