name: Go-SVM's CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          stable: true
          go-version: "1.15"
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Download SVM artifacts
        run: |
          set -e
          echo '${{ secrets.GITHUB_TOKEN }}' | gh auth login --with-token
          ./download_artifacts.sh
      - generate-transactions:
        run: |
          set -e
          cd svm/inputs
          ./generate_txs.sh
      - working-directory: svm
        run: go test .
